# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(410, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(410, 480))
        MainWindow.setMaximumSize(QtCore.QSize(410, 480))
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("border-radius: 10%;\n"
"color: rgb(246, 245, 244);\n"
"background-color: rgb(26, 31, 30);")
        MainWindow.setWindowFilePath("")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(-1, 0, 411, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(26, 31, 30);\n"
"color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(10, 230, 71, 41))
        self.pushButton_clear.setMaximumSize(QtCore.QSize(71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setStyleSheet("background-color: rgb(210, 0,30);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 150, 410, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 36, 35);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_num7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num7.setGeometry(QtCore.QRect(10, 280, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num7.setFont(font)
        self.pushButton_num7.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num7.setObjectName("pushButton_num7")
        self.pushButton_num4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num4.setGeometry(QtCore.QRect(10, 330, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num4.setFont(font)
        self.pushButton_num4.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num4.setObjectName("pushButton_num4")
        self.pushButton_num1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num1.setGeometry(QtCore.QRect(10, 380, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num1.setFont(font)
        self.pushButton_num1.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num1.setObjectName("pushButton_num1")
        self.pushButton_num0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num0.setGeometry(QtCore.QRect(10, 430, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num0.setFont(font)
        self.pushButton_num0.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num0.setObjectName("pushButton_num0")
        self.pushButton_num2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num2.setGeometry(QtCore.QRect(90, 380, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num2.setFont(font)
        self.pushButton_num2.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num2.setObjectName("pushButton_num2")
        self.pushButton_dot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_dot.setGeometry(QtCore.QRect(90, 430, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_bracketl = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bracketl.setGeometry(QtCore.QRect(90, 230, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_bracketl.setFont(font)
        self.pushButton_bracketl.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_bracketl.setObjectName("pushButton_bracketl")
        self.pushButton_num5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num5.setGeometry(QtCore.QRect(90, 330, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num5.setFont(font)
        self.pushButton_num5.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num5.setObjectName("pushButton_num5")
        self.pushButton_num8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num8.setGeometry(QtCore.QRect(90, 280, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num8.setFont(font)
        self.pushButton_num8.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num8.setObjectName("pushButton_num8")
        self.pushButton_bracketr = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bracketr.setGeometry(QtCore.QRect(170, 230, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_bracketr.setFont(font)
        self.pushButton_bracketr.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_bracketr.setObjectName("pushButton_bracketr")
        self.pushButton_num3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num3.setGeometry(QtCore.QRect(170, 380, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num3.setFont(font)
        self.pushButton_num3.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num3.setObjectName("pushButton_num3")
        self.pushButton_num9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num9.setGeometry(QtCore.QRect(170, 280, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num9.setFont(font)
        self.pushButton_num9.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num9.setObjectName("pushButton_num9")
        self.pushButton_percent = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_percent.setGeometry(QtCore.QRect(170, 430, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_percent.setFont(font)
        self.pushButton_percent.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_percent.setObjectName("pushButton_percent")
        self.pushButton_num6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_num6.setGeometry(QtCore.QRect(170, 330, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_num6.setFont(font)
        self.pushButton_num6.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_num6.setObjectName("pushButton_num6")
        self.pushButton_mod = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mod.setGeometry(QtCore.QRect(250, 230, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mod.setFont(font)
        self.pushButton_mod.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_mod.setObjectName("pushButton_mod")
        self.pushButton_sub = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_sub.setGeometry(QtCore.QRect(250, 380, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sub.setFont(font)
        self.pushButton_sub.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_sub.setObjectName("pushButton_sub")
        self.pushButton_div = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_div.setGeometry(QtCore.QRect(250, 280, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_div.setFont(font)
        self.pushButton_div.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_div.setObjectName("pushButton_div")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(250, 430, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_mul = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mul.setGeometry(QtCore.QRect(250, 330, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_mul.setFont(font)
        self.pushButton_mul.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_pi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pi.setGeometry(QtCore.QRect(330, 230, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pi.setFont(font)
        self.pushButton_pi.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_pi.setObjectName("pushButton_pi")
        self.pushButton_res = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_res.setGeometry(QtCore.QRect(330, 380, 71, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_res.setFont(font)
        self.pushButton_res.setStyleSheet("background-color: rgb(0, 110, 0);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_res.setObjectName("pushButton_res")
        self.pushButton_root = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_root.setGeometry(QtCore.QRect(330, 280, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_root.setFont(font)
        self.pushButton_root.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_root.setObjectName("pushButton_root")
        self.pushButton_pow = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pow.setGeometry(QtCore.QRect(330, 330, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_pow.setFont(font)
        self.pushButton_pow.setStyleSheet("background-color: rgb(46, 51, 50);\n"
"color: white;\n"
"border-radius: 5%;\n"
"border: 1px solid  rgb(0, 0, 0);")
        self.pushButton_pow.setObjectName("pushButton_pow")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 60, 31, 30))
        self.pushButton.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 100, 31, 30))
        self.pushButton_2.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 20, 31, 30))
        self.pushButton_4.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 0, 121, 29))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.textBrowser.zoomIn) # type: ignore
        self.pushButton_2.clicked.connect(self.textBrowser.zoomOut) # type: ignore
        self.pushButton_4.clicked.connect(self.textBrowser.clear) # type: ignore
        self.pushButton_4.clicked['bool'].connect(self.lineEdit.clear) # type: ignore
        self.pushButton.toggled['bool'].connect(self.lineEdit.selectAll) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_clear.setText(_translate("MainWindow", "⌫"))
        self.pushButton_num7.setText(_translate("MainWindow", "7"))
        self.pushButton_num4.setText(_translate("MainWindow", "4"))
        self.pushButton_num1.setText(_translate("MainWindow", "1"))
        self.pushButton_num0.setText(_translate("MainWindow", "0"))
        self.pushButton_num2.setText(_translate("MainWindow", "2"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_bracketl.setText(_translate("MainWindow", "("))
        self.pushButton_num5.setText(_translate("MainWindow", "5"))
        self.pushButton_num8.setText(_translate("MainWindow", "8"))
        self.pushButton_bracketr.setText(_translate("MainWindow", ")"))
        self.pushButton_num3.setText(_translate("MainWindow", "3"))
        self.pushButton_num9.setText(_translate("MainWindow", "9"))
        self.pushButton_percent.setText(_translate("MainWindow", "%"))
        self.pushButton_num6.setText(_translate("MainWindow", "6"))
        self.pushButton_mod.setText(_translate("MainWindow", "mod"))
        self.pushButton_sub.setText(_translate("MainWindow", "-"))
        self.pushButton_div.setText(_translate("MainWindow", "÷"))
        self.pushButton_add.setText(_translate("MainWindow", "+"))
        self.pushButton_mul.setText(_translate("MainWindow", "×"))
        self.pushButton_pi.setText(_translate("MainWindow", "Π"))
        self.pushButton_res.setText(_translate("MainWindow", "="))
        self.pushButton_root.setText(_translate("MainWindow", "√"))
        self.pushButton_pow.setText(_translate("MainWindow", "xˣ"))
        self.pushButton.setText(_translate("MainWindow", "Ꙙ"))
        self.pushButton_2.setText(_translate("MainWindow", "ꙙ"))
        self.pushButton_4.setText(_translate("MainWindow", "↻"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Basic"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Advansed"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Financial"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Programming"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Keyboard"))
